### ISSUE TITLE
Update to olcf-jupyter.rst

### ISSUE THREAD

**Issue by LDAmorim** [AMReX-Astro/workflow#4] opened 2020-05-13 18:19 UTC
Hi,
Thanks for this very cool repo and instructions.
I found your file: https://github.com/AMReX-Astro/workflow/blob/f376a31c62e9d93de6e44865aafb1cb8d812c306/sphinx_docs/source/olcf-jupyter.rst.
And I just implemented it to use jupyter lab, however, I had 2 minor issues.

One is actually mentioned in: https://github.com/conda/conda/issues/7980 and I used the workaround that they expressed via introducing above your instructions point 2 the `source` line:

```
2. Next, we need to make sure that the environment will be available when we launch our jupyter session::

    source /sw/summit/python/3.7/anaconda3/5.3.0/etc/profile.d/conda.sh
    conda activate my_env
    ipython kernel install --user --name=my_env
    conda deactivate my_env 
```

The path for conda.sh was that one because prior to any `conda` commands (i.e. before following your point 1), I ran `
module load python/3.7.0-anaconda3-5.3.0`. 

The second change was that I had to open in my browser (safari) `localhost:8888/tree` instead of just `localhost:8888`, otherwise I would get the error message in: https://github.com/jupyterlab/jupyterlab/issues/8164.

I thought I should open this issue here, and ask if there are better fixes for these issues and if you want me to add these lines to olcf-jupyter.rst (as notes probably).

Thank you again for the very helpful instructions,
Diana

**Comment by harpolea** [comment] 2020-05-13 18:38
Hi Diana,

Thanks for your suggestions! So I just checked my `.bashrc` on summit and I have 
```
. /sw/summit/python/3.7/anaconda3/5.3.0/etc/profile.d/conda.sh
```
in there already, which I assume I must have put there at some point in order to get conda to run correctly. The issue you linked to says that this is only a problem when `conda activate my_env` is executed in a script. I have only ever run this by running the commands directly in the terminal - did you find that you needed to include the `conda.sh` script in that case, or were you running things in a script?

I have run this in Safari on MacOS and Firefox and Chrome on Ubuntu and have always been able to just open the browser at `localhost:8888`, so I'm not sure the problem is with the address. If you're getting that error message, it suggests you have another Jupyter session open which is using the same port. You can fix this by opening the ssh session with another port on your local machine, e.g.
```
ssh -N -L localhost:8887:login1:8888 username@summit.olcf.ornl.gov
```
then you'd open up `localhost:8887` in your browser.

**Comment by LDAmorim** [comment] 2020-05-13 20:52
Hi @harpolea ! Thanks for the super quick reply.

I think your option does the same as the "source" command I found, but it is a great idea to add it to .bashrc, instead of repeating it everytime.
I found the issue above, because there wasn't that line on my `.bashrc`, when I was running those commands on the Summit login node directly. To create the environment. Not in a script.

I think I understood the same from the issue that you wrote.
But even after I killed all processes (including terminal - shell -  and safari) I still had that problem. Right after I saw the issue, I just opened another tab and added the `tree` part, without doing anything else, and it worked. So it might have been something else.

Thanks for the note on the change of the localhost! I will try that next time that I find this issue.

Cheers

**Comment by harpolea** [comment] 2020-05-13 21:02
Ok, interesting. I'll add a note to the page telling the user to include the `conda.sh` script (either through `source` or in their `.bashrc` file). 

It might be that there is something else on your system that is set up to use port 8888? To be honest this is not something I've come across before, but good to hear you have a solution that works for you! FYI, the trick with using a different port for `localhost` is particularly useful if you wanted to connect to multiple JupterLab instances which are e.g. hosted on different remote machines 🙂

**Comment by LDAmorim** [comment] 2020-05-13 21:13
Thanks @harpolea !
That is very useful indeed, thanks for the multiple `localhost`s note :)

**Comment by zingale** [comment] 2021-09-28 18:21
I think that now that there is a jupyterhub at OLCF, we can close this.

**Closed by zingale** 2021-09-28 18:21 UTC
